version: '2'

services:
    webserver:
        image: nginx:stable
        ports:
            - "80:80"
        environment:
           NGINX_HOST: dev.local
           NGINX_PORT: 80
           TERM: xterm
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./services/nginx/conf.d/vhost-default.conf:/etc/nginx/conf.d/default.conf
            # - ./services/nginx/conf.d/vhost-shopware.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - phpfpm
        links:
            - db
            - phpfpm
            - mailfetcher

    phpfpm:
        image: netshops/dev_php_fpm_ioncube
        environment:
           TERM: xterm
        volumes:
            - ./services/phpfpm/00-custom.ini:/etc/php/7.0/fpm/conf.d/00-custom.ini
            - ./services/phpfpm/90-custom.ini:/etc/php/7.0/fpm/conf.d/90-custom.ini
            - /var/www/html

    db:
        image: percona:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
            TERM: xterm
        volumes:
            - ./services/percona/percona-server.conf.d/mysql.cnf:/etc/mysql/percona-server.conf.d/mysql.cnf
            - ./services/percona/percona-server.conf.d/mysql_safe.cnf:/etc/mysql/percona-server.conf.d/mysql_safe.cnf

    mailfetcher:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        environment:
            MH_HOSTNAME: mail.dev.local
            TERM: xterm